### ISSUE TITLE
关于代码中注释的一些问题

### ISSUE THREAD

**Issue by geralt-write-code** [ChenShihuan/Finger-vein-recognition#1]
同学你好，我下载了你的代码以后，发现里面有许多注释，其中大部分取消注释以后修改一下还是可以运行的，但是在gaborfilte.m中代码取消注释以后运行会出现错误，显示错误使用imfuse>parse_inputs，根据提示的错误信息应该是在使用一些自带的函数时输入的矩阵的维数不对，我没有找到解决方法。请问你当时是如何解决这个问题的呢？

**Comment by ChenShihuan** [comment]
> 同学你好，我下载了你的代码以后，发现里面有许多注释，其中大部分取消注释以后修改一下还是可以运行的，但是在gaborfilte.m中代码取消注释以后运行会出现错误，显示错误使用imfuse>parse_inputs，根据提示的错误信息应该是在使用一些自带的函数时输入的矩阵的维数不对，我没有找到解决方法。请问你当时是如何解决这个问题的呢？

这个文件中间那坨注释掉的是没用的。之前是打算用matlab内置的滤波器来做这个算法，但是搞不懂那个东西怎么用，然后就另外找一个滤波器的实现，也就是这一行——

- GabOut = gaborfilter2(Input, 0.035, 0.8, 0, 0);

然后下面这一坨是用不了的不要的——

- %             gaborArray = gabor([4 23],[85 90],'SpatialAspectRatio', 0.33);
- %             GabOut = imgaborfilt(Input,gaborArray);
- %             figure
- %             subplot(2,2,1);
- %             for p = 1:4
- %                 subplot(2,2,p)
- %                 imshow(GabOut(:,:,p),[]);
- %                 theta = gaborArray(p).Orientation;
- %                 lambda = gaborArray(p).Wavelength;
- %                 title(sprintf('Orientation=%d, Wavelength=%d',theta,lambda));
- %             end
- %             figure
- %             imshowpair(GabOut(:,:,4),Input,'montage')
- %             Gabimg = GabOut(:,:,4);
- %             Gabimg = real(Gabimg);
- %             Gabimg(Gabimg<0)=0;
- %             Gabimg = imbinarize(Gabimg);
- %             figure
- %             imshow(Gabimg)
- %             imshowpair(GabOut,Input,'montage')

**Comment by geralt-write-code** [comment]
好的，明白了。顺便在问一下，其他的比如.m文件中的注释掉的部分也都是不需要的吗?
谢谢

**Comment by ChenShihuan** [comment]
> 好的，明白了。顺便在问一下，其他的比如.m文件中的注释掉的部分也都是不需要的吗?
> 谢谢

这个具体还是要你自己判断，我没法在这里一处处指出了，我相信你也有能力根据我下面的描述来判断它们。其它m文件中注释掉的部分有的调试阶段用于输出一部分参数调试完成后就不需要输出的，有的是调试阶段需要输入而调试完成后不需要的，大部分属于以上两种。还有些是不同顺序的方法，最后选择了效果好一些的顺序，而gaborfilte.m里面这种写废了的属于极少数。

**Comment by geralt-write-code** [comment]
好的，非常感谢
